-- Script para crear tablas en Oracle Database
-- Ejecutar como ADMIN

-- Tabla de médicos
CREATE TABLE medicos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    especialidad VARCHAR2(50) NOT NULL,
    cedula VARCHAR2(20) UNIQUE NOT NULL,
    correo VARCHAR2(100) UNIQUE NOT NULL,
    telefono VARCHAR2(15),
    horario VARCHAR2(50),
    consultorio VARCHAR2(20),
    contrasena VARCHAR2(100) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'medico'
);

-- Tabla de pacientes
CREATE TABLE pacientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    curp VARCHAR2(18) UNIQUE NOT NULL,
    telefono VARCHAR2(15),
    matricula VARCHAR2(20) UNIQUE NOT NULL,
    correo VARCHAR2(100) UNIQUE NOT NULL,
    contrasena VARCHAR2(100) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'paciente'
);

-- Tabla de consultas
CREATE TABLE consultas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente NUMBER NOT NULL,
    id_medico NUMBER NOT NULL,
    fecha DATE NOT NULL,
    hora VARCHAR2(10) NOT NULL,
    motivo VARCHAR2(200),
    estado VARCHAR2(20) DEFAULT 'programada',
    diagnostico CLOB,
    tratamiento CLOB,
    observaciones CLOB,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id),
    FOREIGN KEY (id_medico) REFERENCES medicos(id)
);

-- Insertar datos de prueba
INSERT INTO medicos (nombre, especialidad, cedula, correo, telefono, horario, consultorio, contrasena) VALUES
('Dr. Juan Pérez', 'Cardiología', '12345678', 'doctor@test.com', '555-1111', '8:00-16:00', 'Consultorio 1', 'doctor123'),
('Dra. María González', 'Dermatología', '87654321', 'dermatologa@test.com', '555-2222', '9:00-17:00', 'Consultorio 2', 'dermatologa123'),
('Dr. Carlos Rodríguez', 'Pediatría', '11223344', 'pediatra@test.com', '555-3333', '7:00-15:00', 'Consultorio 3', 'pediatra123');

INSERT INTO pacientes (nombre, curp, telefono, matricula, correo, contrasena) VALUES
('María González', 'GONM800101MDFXXX01', '5598765432', 'A123456', 'paciente@test.com', 'paciente123'),
('Juan López', 'LOPJ850515HDFXXX02', '5511223344', 'B789012', 'juan.lopez@test.com', 'juan123'),
('Ana Martínez', 'MARA900320MDFXXX03', '5566778899', 'C345678', 'ana.martinez@test.com', 'ana123');

INSERT INTO consultas (id_paciente, id_medico, fecha, hora, motivo, estado) VALUES
(1, 1, SYSDATE + 1, '09:00', 'Revisión cardiológica de rutina', 'programada'),
(1, 2, SYSDATE + 3, '14:30', 'Consulta por problemas de piel', 'programada'),
(2, 1, SYSDATE + 2, '11:00', 'Evaluación cardíaca por dolor en el pecho', 'programada'),
(2, 3, SYSDATE + 5, '10:00', 'Consulta pediátrica para su hijo', 'programada'),
(3, 2, SYSDATE + 1, '16:00', 'Revisión dermatológica anual', 'programada');

COMMIT;
